### ISSUE TITLE
Viewer error

### ISSUE THREAD

**Issue by qvistering** [shoaib-jamal/rebornxp#20]
**Describe the bug**
It's strange because at one point this was working fine, but now it isn't, even on a brand new clone of the project. After a fresh clone of the project, I am getting a viewer error (see below). Any help would be appreciated. I'm just a hobby developer, working on something for nostalgic purposes.

**To Reproduce**
1. Clone the project
2. Get it running
3. Click on "My Computer" or any file that would open a Finder window.
4. View error

**Expected behavior**

**Screenshots**
![Screenshot 2024-04-14 at 1 58 06 PM](https://github.com/shoaib-jamal/rebornxp/assets/142653470/1d136b52-f140-4eb9-8b31-f79e42d24a7a)

`[HMR][Svelte] Unrecoverable HMR error in <Viewer>: next update will trigger a full reload
logError @ proxy.js?v=9c918bd9:15
Proxy<Viewer> @ proxy.js?v=9c918bd9:380
create_content_slot @ my_computer.svelte:312
create_slot @ chunk-5K467XFM.js?v=9c918bd9:70
create_fragment @ Window.svelte:285
init @ chunk-5K467XFM.js?v=9c918bd9:1723
Window @ Window.svelte:268
createProxiedComponent @ svelte-hooks.js?v=9c918bd9:341
ProxyComponent @ proxy.js?v=9c918bd9:242
Proxy<Window> @ proxy.js?v=9c918bd9:349
create_fragment @ my_computer.svelte:261
init @ chunk-5K467XFM.js?v=9c918bd9:1723
My_computer @ my_computer.svelte:40
createProxiedComponent @ svelte-hooks.js?v=9c918bd9:341
ProxyComponent @ proxy.js?v=9c918bd9:242
Proxy<My_computer> @ proxy.js?v=9c918bd9:349
launch @ work_space.svelte:38
await in launch (async)
(anonymous) @ work_space.svelte:19
set @ chunk-CS6XKSN7.js?v=9c918bd9:30
open @ desktop_folder.svelte:108
dblclick_handler @ desktop_folder.svelte:237
dblclick_handler @ desktop_folder.svelte:241
Show 12 more frames
Show less
viewer.svelte:32 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'location')
    at instance (viewer.svelte:32:83)
    at init (chunk-5K467XFM.js?v=9c918bd9:1710:23)
    at new Viewer (viewer.svelte:69:19)
    at createProxiedComponent (svelte-hooks.js?v=9c918bd9:341:9)
    at new ProxyComponent (proxy.js?v=9c918bd9:242:7)
    at new Proxy<Viewer> (proxy.js?v=9c918bd9:349:11)
    at Array.create_content_slot (my_computer.svelte:312:82)
    at create_slot (chunk-5K467XFM.js?v=9c918bd9:70:25)
    at create_fragment (Window.svelte:285:119)
    at init (chunk-5K467XFM.js?v=9c918bd9:1723:35)
    at new Window (Window.svelte:268:24)
    at createProxiedComponent (svelte-hooks.js?v=9c918bd9:341:9)
    at new ProxyComponent (proxy.js?v=9c918bd9:242:7)
    at new Proxy<Window> (proxy.js?v=9c918bd9:349:11)
    at create_fragment (my_computer.svelte:261:69)
    at init (chunk-5K467XFM.js?v=9c918bd9:1723:35)
instance @ viewer.svelte:32
init @ chunk-5K467XFM.js?v=9c918bd9:1710
Viewer @ viewer.svelte:69
createProxiedComponent @ svelte-hooks.js?v=9c918bd9:341
ProxyComponent @ proxy.js?v=9c918bd9:242
Proxy<Viewer> @ proxy.js?v=9c918bd9:349
create_content_slot @ my_computer.svelte:312
create_slot @ chunk-5K467XFM.js?v=9c918bd9:70
create_fragment @ Window.svelte:285
init @ chunk-5K467XFM.js?v=9c918bd9:1723
Window @ Window.svelte:268
createProxiedComponent @ svelte-hooks.js?v=9c918bd9:341
ProxyComponent @ proxy.js?v=9c918bd9:242
Proxy<Window> @ proxy.js?v=9c918bd9:349
create_fragment @ my_computer.svelte:261
init @ chunk-5K467XFM.js?v=9c918bd9:1723
My_computer @ my_computer.svelte:40
createProxiedComponent @ svelte-hooks.js?v=9c918bd9:341
ProxyComponent @ proxy.js?v=9c918bd9:242
Proxy<My_computer> @ proxy.js?v=9c918bd9:349
launch @ work_space.svelte:38
await in launch (async)
(anonymous) @ work_space.svelte:19
set @ chunk-CS6XKSN7.js?v=9c918bd9:30
open @ desktop_folder.svelte:108
dblclick_handler @ desktop_folder.svelte:237
dblclick_handler @ desktop_folder.svelte:241
Show 14 more frames
Show less`

**Comment by shoaib-jamal** [comment]
May I know your NodeJS version? and which command you used to download packages?

**Comment by qvistering** [comment]
I'm using Node v20.10.0

I did the following to get clone, download the packages, and run the project:

`
gh repo clone shoaib-jamal/rebornxp
cd rebornxp/
npm install
npm audit fix
npm run dev
`

**Comment by shoaib-jamal** [comment]
The command `npm audit fix` breaks packages, and thus not recommended since the code is currently not compatible with newer version of the package versions.

Just run without audit after installing the packages.

**Comment by qvistering** [comment]
i see. thank you!
